=== arfc/saltproc/saltproc/input_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/arfc/saltproc",
    "title": "SaltProc input file schema",
    "type": "object",
    "properties": {
        "proc_input_file": {
            "description": "File containing processing system objects",
            "type": "string",
            "pattern": "^(.*)\\.json$"
        },
        "dot_input_file": {
            "description": "Graph file containing processing system structure",
            "type": "string",
            "pattern": "^(.*)\\.dot$"
        },
        "output_path": {
            "description": "Path output data storing folder",
            "type": "string",
            "pattern": "^\\.\\/(.*)$"
        },
        "num_depsteps": {
            "description": "Number of steps for constant power and depletion interval case",
            "type": "number"
        },
        "depcode": {
            "description": "Depcode class input parameters",
            "type": "object",
            "properties": {
                "codename": {
                    "description": "Name of depletion code",
                    "type": "string",
                    "enum": ["serpent", "openmc"]},
                "exec_path": {
                    "description": "Path to depletion code executable",
                    "type": "string" },
                "template_input_file_path": {
                    "description": "Path(s) to user's template depletion code input file(s) with reactor model"},
                "npop": {
                    "description": "Number of neutrons per generation",
                    "type": "number",
                    "minimum": 0},
                "active_cycles": {
                    "description": "number of active generations",
                    "type": "number",
                    "minimum": 0},
                "inactive_cycles": {
                    "description": "Number of inactive generations",
                    "type": "number",
                    "minimum": 0},
                "geo_file_paths": {
                    "description": "Path(s) to geometry file(s) to switch to in depletion code runs",
                    "type": "array",
                    "items": { "type": "string"},
                    "minItems": 1,
                    "uniqueItems": false
                }
            },
            "allOf": [
                {
                    "if": {
                        "properties": { "codename": { "const": "serpent" } }
                    },
                    "then": {
                        "properties": {
                            "template_input_file_path": {
                                "type": "string",
                                "pattern": "^\\.\\/(.*)$"}
                        }
                    }
                },
                {
                    "if": {
                        "properties": { "codename": { "const": "openmc" } }
                    },
                    "then": {
                        "properties": {
                            "template_input_file_path": {
                                "type": "object",
                                "propterties": {
                                    "settings": {
                                        "type": "string",
                                        "pattern": "^\\.\\/(.*)\\.xml$"},
                                    "geometry": {
                                        "type": "string",
                                        "pattern": "^\\.\\/(.*)\\.xml$"},
                                    "materials": {
                                        "type": "string",
                                        "pattern": "^\\.\\/(.*)\\.xml$"},
                                    "plots": {
                                        "type": "string",
                                        "pattern": "^\\.\\/(.*)\\.xml$"},
                                    "chain_file": {
                                        "type": "string",
                                        "pattern": "^\\.\\/(.*)\\.xml$"}
                                },

                                "required": ["settings", "geometry", "materials", "chain_file"]
                            }
                        }
                    }
                }

            ],
            "required": ["codename", "exec_path", "template_input_file_path", "npop", "active_cycles","inactive_cycles", "geo_file_paths"]
        },
       "simulation": {
           "description": "Simulation class input parameters",
           "type": "object",
           "properties": {
               "sim_name": {
                   "description": "Name of simulation",
                   "type": "string"},
               "db_name": {
                   "description": "Output HDF5 database file name",
                   "type": "string",
                    "pattern": "^(.*)\\.h5$"},
               "restart_flag": {
                   "description": "Restart simulation from the step when it stopped?",
                   "type": "boolean"},
               "adjust_geo": {
                   "description": "switch to another geometry when keff drops below 1?",
                   "type": "boolean"}
           },
           "requires": ["sim_name", "db_name", "restart_flag", "adjust_geo"]
       },
       "reactor": {
           "description": "Reactor class input parameters",
           "type": "object",
           "properties": {
               "volume": {
                   "description": "reactor core volume [cm^3]",
                   "type": "number",
                    "minimum": 0},
               "mass_flowrate": {
                   "description": "Salt mass flowrate through reactor core [g/s]",
                   "type": "number",
                    "minimum": 0 },
               "power_levels": {
                   "description": "Reactor power or power step list durng depletion step [W]",
                   "type": "array",
                   "items": { "type": "number",
                    "minimum": 0},
                   "minItems": 1,
                   "uniqueItems": false
                },
               "dep_step_length_cumulative": {
                   "description": "Depletion step length(s) (cumulative) [d]",
                   "type": "array",
                   "items": { "type": "number",
                    "minimum": 0},
                   "minItems": 1,
                   "uniqueItems": false
                }
           },
           "required": ["volume", "mass_flowrate", "power_levels", "dep_step_length_cumulative"]
       }
    },
    "required": ["proc_input_file", "dot_input_file", "output_path", "depcode", "simulation", "reactor"]
}

=== arfc/saltproc/tests/integration_tests/run_constant_reprocessing/test_input.json
{
   "proc_input_file": "test_processes.json",
   "dot_input_file": "test_paths.dot",
   "output_path": ".",
   "num_depsteps": 2,
   "depcode": {
       "codename": "serpent",
       "exec_path": "sss2",
       "template_input_file_path": "./test_input.ini",
       "npop": 50,
       "active_cycles": 20,
       "inactive_cycles": 20,
       "geo_file_paths": ["./test_geometry_base.ini"]
   },
   "simulation": {
       "sim_name": "tap_integration_test",
       "db_name": "test_db.h5",
       "restart_flag": false,
       "adjust_geo": false
   },
   "reactor": {
       "volume": 1.0,
       "mass_flowrate": 9.92E+6,
       "power_levels": [ 1.250E+9 ],
       "dep_step_length_cumulative": [ 5 ]
   }
}
